"""Initial schema energy_meters and measurements table.

Revision ID: 001_initial
Revises:
Create Date: 2026-04-18

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS energy_meters'))
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'))

    op.create_table(
        "measurements",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v1()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("local_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("voltage", sa.Double(), nullable=False),
        sa.Column("current", sa.Double(), nullable=False),
        sa.Column("active_power", sa.Double(), nullable=False),
        sa.Column("active_energy", sa.Double(), nullable=False),
        sa.Column("frequency", sa.Double(), nullable=False),
        sa.Column("power_factor", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="energy_meters",
        comment="Electrical measurements ingested from energy meters (time series).",
    )

    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.id IS "
            "'Primary key; UUID version 1 generated by PostgreSQL (uuid_generate_v1).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.created_at IS "
            "'Row insertion time in the database (timestamptz, server default now()).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.local_time IS "
            "'Instant when the sample was taken on the meter or device clock (timestamptz).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.voltage IS "
            "'Voltage in volts (V).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.current IS "
            "'Current in amperes (A).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.active_power IS "
            "'Active (real) power in watts (W).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.active_energy IS "
            "'Cumulative active energy register reading in watt-hours (Wh).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.frequency IS "
            "'AC line frequency in hertz (Hz).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.measurements.power_factor IS "
            "'Power factor (dimensionless; typically between 0 and 1).'"
        )
    )


def downgrade() -> None:
    op.drop_table("measurements", schema="energy_meters")
    op.execute(sa.text("DROP SCHEMA IF EXISTS energy_meters CASCADE"))
