"""Devices catalog and FK from measurements.device_id.

Revision ID: 004_devices_catalog
Revises: 003_index_local_time
Create Date: 2026-04-18

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "004_devices_catalog"
down_revision: str | Sequence[str] | None = "003_index_local_time"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "devices",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v1()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("serial_number", sa.String(length=128), nullable=True),
        sa.Column("meter_model", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number", name="uq_devices_serial_number"),
        schema="energy_meters",
        comment="Catalog of physical or logical energy meters that emit measurements.",
    )

    op.execute(
        sa.text(
            "INSERT INTO energy_meters.devices (id, created_at, is_active) "
            "SELECT DISTINCT m.device_id, now(), true "
            "FROM energy_meters.measurements m "
            "WHERE NOT EXISTS (SELECT 1 FROM energy_meters.devices d WHERE d.id = m.device_id)"
        )
    )

    op.create_foreign_key(
        "fk_measurements_device_id_devices",
        "measurements",
        "devices",
        ["device_id"],
        ["id"],
        source_schema="energy_meters",
        referent_schema="energy_meters",
        ondelete="RESTRICT",
    )

    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.id IS "
            "'Primary key; UUID v1 generated by default for new rows.'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.created_at IS "
            "'When this catalog row was created (timestamptz, server default now()).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.name IS "
            "'Human-readable label for dashboards and operations.'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.serial_number IS "
            "'Manufacturer or asset serial; unique when present.'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.meter_model IS "
            "'Model or part number of the metering hardware.'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.notes IS "
            "'Free-form description, installation notes, or internal references.'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.timezone IS "
            "'IANA timezone for interpreting device local wall time (e.g. America/Bogota).'"
        )
    )
    op.execute(
        sa.text(
            "COMMENT ON COLUMN energy_meters.devices.is_active IS "
            "'False when the device is retired or must not receive new measurements.'"
        )
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_measurements_device_id_devices",
        "measurements",
        schema="energy_meters",
        type_="foreignkey",
    )
    op.drop_table("devices", schema="energy_meters")
